config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#index'
  resources :categories do
    resources :restaurants
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @restaurants = Restaurant.where(category_id: @category.id)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.delete
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_category, only: %i[new create]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.category = @category
    @restaurant.save ? (redirect_to category_path(@category)) : (render :new)
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/index.html.erb
<div class="container">
  <% @categories.each do |c| %>
    <%= link_to category_path(c) do %>
      <h1><%= c.name %></h1>
    <% end %>
    <%= link_to category_path(c), method: :delete do %>
      <button>Delete</button>
    <% end %>
  <% end  %>
</div>

<h3><%= link_to 'Create new category', new_category_path  %></h3>

app/views/categories/new.html.erb
<%= simple_form_for @category do |c| %>
  <%= c.input :name %>
  <%= c.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% @restaurants.each do |r| %>
  <h2><%= r.name %></h2>
  <h3><%= r.address %></h3>
<% end %>

<%= link_to 'Add new restaurant', new_category_restaurant_path(@category) %>
<%= link_to 'home', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRestaurant0902</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants!</h1>
<% @restaurants.each do |r| %>
  <%= link_to restaurant_path(r) do %>
    <h2><%= r.name %></h2>
    <h2><%= r.address %></h2>
  <% end %>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for [@category, @restaurant] do |r| %>
  <%= r.input :name %>
  <%= r.input :address %>
  <%= r.button :submit %>
<% end %>